=== Leantas/L2PacketAnalyzer/config/schemata/mapping.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.l2emu-unique.net" xmlns="http://www.l2emu-unique.net"
	elementFormDefault="qualified">

	<xs:element name="mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="client" type="wrapperType" />
				<xs:element name="server" type="wrapperType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="delimitedHexBytes">
		<xs:restriction base="xs:token">
			<xs:pattern value="[0-9A-F]{2}( [0-9A-F]{2})*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="packetWithOpcodesType">
		<xs:complexContent>
			<xs:extension base="packetType">
				<xs:attribute name="opcodePrefix" type="delimitedHexBytes" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="packetType">
		<xs:attribute name="id" type="xs:token" use="required" />
	</xs:complexType>

	<xs:complexType name="wrapperType">
		<xs:sequence>
			<xs:element name="removedPacket" type="packetType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="packet" type="packetWithOpcodesType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Leantas/L2PacketAnalyzer/config/packets/c5_oath_of_blood_update_1/opcode_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../schemata/mapping.xsd">
	<client>
		<packet opcodePrefix="D0 22 00" id="216" />
		<packet opcodePrefix="D0 23 00" id="217" />
		<packet opcodePrefix="D0 24 00" id="218" />
	</client>
	<server>
		<packet opcodePrefix="FE 43 00" id="356" />
		<packet opcodePrefix="FE 44 00" id="357" />
		<packet opcodePrefix="FE 45 00" id="358" />
		<packet opcodePrefix="FE 46 00" id="359" />
		<packet opcodePrefix="FE 47 00" id="360" />
	</server>
</mapping>

=== Leantas/L2PacketAnalyzer/config/packets/goddess_of_destruction/opcode_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../schemata/mapping.xsd">
	<client>
		<packet opcodePrefix="D0 36 00" id="231" />
		<packet opcodePrefix="D0 5A 00" id="277" />
		<packet opcodePrefix="D0 7F 00" id="353" />
		<packet opcodePrefix="D0 80 00" id="354" />
		<packet opcodePrefix="D0 81 00" id="355" />
		<packet opcodePrefix="D0 82 00" id="356" />
		<packet opcodePrefix="D0 91 00" id="357" />
		<packet opcodePrefix="D0 92 00" id="358" />
		<packet opcodePrefix="D0 93 00" id="359" />
		<packet opcodePrefix="D0 94 00" id="360" />
		<packet opcodePrefix="D0 95 00" id="361" />
		<packet opcodePrefix="D0 96 00 02 00 00 00" id="362" />
		<packet opcodePrefix="D0 96 00 03 00 00 00" id="363" />
		<packet opcodePrefix="D0 96 00 04 00 00 00" id="364" />
		<packet opcodePrefix="D0 97 00" id="365" />
		<packet opcodePrefix="D0 98 00" id="366" />
		<packet opcodePrefix="D0 99 00" id="367" />
		<packet opcodePrefix="D0 9A 00" id="368" />
		<packet opcodePrefix="D0 9B 00" id="369" />
		<packet opcodePrefix="D0 9C 00" id="370" />
		<packet opcodePrefix="D0 9D 00" id="371" />
		<packet opcodePrefix="D0 9E 00" id="372" />
		<packet opcodePrefix="D0 9F 00" id="373" />
		<packet opcodePrefix="D0 A0 00" id="374" />
		<packet opcodePrefix="D0 A1 00" id="375" />
		<packet opcodePrefix="D0 A2 00" id="376" />
		<packet opcodePrefix="D0 A3 00" id="377" />
		<packet opcodePrefix="D0 A4 00" id="378" />
		<packet opcodePrefix="D0 A5 00" id="379" />
		<packet opcodePrefix="D0 A6 00" id="380" />
		<packet opcodePrefix="D0 A7 00" id="381" />
		<packet opcodePrefix="D0 A8 00" id="462" />
		<packet opcodePrefix="D0 A9 00" id="463" />
		<packet opcodePrefix="D0 AA 00" id="464" />
		<packet opcodePrefix="D0 AB 00" id="465" />
		<packet opcodePrefix="D0 AC 00" id="348" />
		<packet opcodePrefix="D0 AD 00" id="322" />
		<packet opcodePrefix="D0 AE 00" id="323" />
		<packet opcodePrefix="D0 AF 00" id="324" />
		<packet opcodePrefix="D0 B0 00" id="349" />
		<packet opcodePrefix="D0 B1 00" id="346" />
		<packet opcodePrefix="D0 B2 00" id="347" />
		<packet opcodePrefix="D0 B3 00" id="382" />
		<packet opcodePrefix="D0 B4 00" id="383" />
		<packet opcodePrefix="D0 B5 00" id="384" />
		<packet opcodePrefix="D0 B7 00" id="385" />
		<packet opcodePrefix="D0 B8 00" id="386" />
		<packet opcodePrefix="D0 B9 00" id="387" />
		<packet opcodePrefix="D0 BA 00" id="466" />
		<packet opcodePrefix="D0 BB 00" id="388" />
		<packet opcodePrefix="D0 BC 00" id="389" />
		<packet opcodePrefix="D0 BD 00" id="390" />
		<packet opcodePrefix="D0 BE 00" id="391" />
		<packet opcodePrefix="D0 BF 00" id="392" />
		<packet opcodePrefix="D0 C0 00" id="393" />
		<packet opcodePrefix="D0 C1 00" id="394" />
		<packet opcodePrefix="D0 C2 00" id="395" />
		<packet opcodePrefix="D0 CC 00" id="405" />
		<packet opcodePrefix="D0 CD 00" id="406" />
		<packet opcodePrefix="D0 CE 00" id="407" />
		<packet opcodePrefix="D0 CF 00" id="408" />
	</client>
	<server>
		<!-- Replaced by SM_FRIEND_ADD_REQUEST_RESULT and SM_FRIEND_REMOVE since GoD -->
		<removedPacket id="SM_L2_FRIEND" />
		<packet opcodePrefix="FE 00 00" id="533" />
		<packet opcodePrefix="FE BD 00" id="492" />
		<packet opcodePrefix="FE DF 00" id="538" />
		<packet opcodePrefix="FE E0 00" id="539" />
		<packet opcodePrefix="FE E1 00" id="540" />
		<packet opcodePrefix="FE E2 00" id="515" />
		<packet opcodePrefix="FE E3 00" id="516" />
		<packet opcodePrefix="FE E4 00" id="517" />
		<packet opcodePrefix="FE E5 00" id="541" />
		<packet opcodePrefix="FE E6 00" id="542" />
		<packet opcodePrefix="FE E7 00" id="543" />
		<packet opcodePrefix="FE E8 00" id="544" />
		<packet opcodePrefix="FE E9 00" id="545" />
		<packet opcodePrefix="FE EA 00" id="546" />
		<packet opcodePrefix="FE EB 00" id="547" />
		<packet opcodePrefix="FE EC 00" id="548" />
		<packet opcodePrefix="FE ED 00" id="549" />
		<packet opcodePrefix="FE EE 00" id="550" />
		<packet opcodePrefix="FE EF 00" id="551" />
		<packet opcodePrefix="FE F0 00" id="552" />
		<packet opcodePrefix="FE F1 00" id="553" />
		<packet opcodePrefix="FE F2 00" id="554" />
		<packet opcodePrefix="FE F3 00" id="555" />
		<packet opcodePrefix="FE F4 00" id="556" />
		<packet opcodePrefix="FE F5 00" id="557" />
		<packet opcodePrefix="FE F6 00" id="558" />
		<packet opcodePrefix="FE F7 00" id="559" />
		<packet opcodePrefix="FE F8 00" id="560" />
		<packet opcodePrefix="FE F9 00" id="561" />
		<packet opcodePrefix="FE FA 00" id="562" />
		<packet opcodePrefix="FE FB 00" id="563" />
		<packet opcodePrefix="FE FC 00" id="564" />
		<packet opcodePrefix="FE FD 00" id="565" />
		<packet opcodePrefix="FE FE 00" id="566" />
		<packet opcodePrefix="FE FF 00" id="567" />
		<packet opcodePrefix="FE 00 01" id="568" />
		<packet opcodePrefix="FE 01 01" id="569" />
		<packet opcodePrefix="FE 02 01" id="570" />
		<packet opcodePrefix="FE 03 01" id="682" />
		<packet opcodePrefix="FE 04 01" id="683" />
		<packet opcodePrefix="FE 05 01" id="684" />
		<packet opcodePrefix="FE 06 01" id="685" />
		<packet opcodePrefix="FE 07 01" id="686" />
		<packet opcodePrefix="FE 08 01" id="687" />
		<packet opcodePrefix="FE 09 01" id="521" />
		<packet opcodePrefix="FE 0A 01" id="522" />
		<packet opcodePrefix="FE 0B 01" id="523" />
		<packet opcodePrefix="FE 0C 01" id="572" />
		<packet opcodePrefix="FE 0D 01" id="573" />
		<packet opcodePrefix="FE 0E 01" id="574" />
		<packet opcodePrefix="FE 0F 01" id="575" />
		<packet opcodePrefix="FE 10 01" id="518" />
		<packet opcodePrefix="FE 11 01" id="519" />
		<packet opcodePrefix="FE 12 01" id="520" />
		<packet opcodePrefix="FE 13 01" id="576" />
		<packet opcodePrefix="FE 14 01" id="577" />
		<packet opcodePrefix="FE 15 01" id="456" />
		<packet opcodePrefix="FE 16 01" id="578" />
		<packet opcodePrefix="FE 17 01" id="579" />
		<packet opcodePrefix="FE 18 01" id="580" />
		<packet opcodePrefix="FE 19 01" id="581" />
		<packet opcodePrefix="FE 1A 01" id="582" />
		<packet opcodePrefix="FE 1B 01" id="688" />
		<packet opcodePrefix="FE 1C 01" id="583" />
		<packet opcodePrefix="FE 1D 01" id="584" />
		<packet opcodePrefix="FE 1E 01" id="585" />
		<packet opcodePrefix="FE 1F 01" id="586" />
		<packet opcodePrefix="FE 20 01" id="587" />
		<packet opcodePrefix="FE 21 01" id="588" />
		<packet opcodePrefix="FE 22 01" id="589" />
		<packet opcodePrefix="FE 23 01" id="601" />
		<packet opcodePrefix="FE 24 01" id="602" />
		<packet opcodePrefix="FE 25 01" id="603" />
		<packet opcodePrefix="FE 26 01" id="604" />
		<packet opcodePrefix="FE 27 01" id="617" />
	</server>
</mapping>

=== Leantas/L2PacketAnalyzer/config/packets/freya/opcode_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../schemata/mapping.xsd">
	<client>
		<packet opcodePrefix="D0 73 00" id="314" />
		<packet opcodePrefix="D0 74 00" id="315" />
		<packet opcodePrefix="D0 78 00" id="316" />
		<packet opcodePrefix="D0 79 00" id="317" />
		<packet opcodePrefix="D0 7A 00" id="318" />
		<packet opcodePrefix="D0 7B 00" id="310" />
		<packet opcodePrefix="D0 7C 00" id="319" />
		<packet opcodePrefix="D0 7D 00" id="320" />
		<packet opcodePrefix="D0 7E 00" id="321" />
		<packet opcodePrefix="D0 7F 00" id="288" />
		<packet opcodePrefix="D0 80 00" id="289" />
		<packet opcodePrefix="D0 81 00" id="290" />
		<packet opcodePrefix="D0 82 00" id="291" />
		<packet opcodePrefix="D0 83 00" id="309" />
		<packet opcodePrefix="D0 84 00" id="311" />
		<packet opcodePrefix="D0 85 00" id="312" />
		<packet opcodePrefix="D0 86 00" id="313" />
	</client>
	<server>
		<packet opcodePrefix="FE B5 00" id="487" />
		<packet opcodePrefix="FE B8 00" id="488" />
		<packet opcodePrefix="FE B9 00" id="489" />
		<packet opcodePrefix="FE BA 00" id="490" />
		<packet opcodePrefix="FE BB 00" id="491" />
		<packet opcodePrefix="FE BC 00" id="484" />
		<packet opcodePrefix="FE BD 00" id="492" />
		<packet opcodePrefix="FE BE 00" id="493" />
		<packet opcodePrefix="FE BF 00" id="494" />
		<packet opcodePrefix="FE C0 00" id="495" />
		<packet opcodePrefix="FE C1 00" id="496" />
		<packet opcodePrefix="FE C2 00" id="497" />
		<packet opcodePrefix="FE C3 00" id="498" />
		<packet opcodePrefix="FE C4 00" id="499" />
		<packet opcodePrefix="FE C5 00" id="500" />
		<packet opcodePrefix="FE C6 00" id="501" />
		<packet opcodePrefix="FE C7 00" id="502" />
		<packet opcodePrefix="FE C8 00" id="503" />
		<packet opcodePrefix="FE C9 00" id="457" />
		<packet opcodePrefix="FE CA 00" id="458" />
		<packet opcodePrefix="FE CB 00" id="459" />
		<packet opcodePrefix="FE CC 00" id="460" />
		<packet opcodePrefix="FE CD 00" id="537" />
		<packet opcodePrefix="FE CE 00" id="463" />
		<packet opcodePrefix="FE CF 00" id="462" />
		<packet opcodePrefix="FE D0 00" id="466" />
		<packet opcodePrefix="FE D1 00" id="483" />
		<packet opcodePrefix="FE D2 00" id="485" />
		<packet opcodePrefix="FE D3 00" id="486" />
	</server>
</mapping>

=== Leantas/L2PacketAnalyzer/config/packets/lindvior_update_3/opcode_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../schemata/mapping.xsd">
	<client>
		<packet opcodePrefix="D0 F1 00" id="446" />
		<packet opcodePrefix="D0 F2 00" id="447" />
		<packet opcodePrefix="D0 F3 00" id="434" />
	</client>
	<server>
		<packet opcodePrefix="FE 5B 01" id="641" />
		<packet opcodePrefix="FE 5C 01" id="694" />
		<packet opcodePrefix="FE 5D 01" id="695" />
		<packet opcodePrefix="FE 5E 01" id="696" />
		<packet opcodePrefix="FE 5F 01" id="645" />
		<packet opcodePrefix="FE 60 01" id="527" />
		<packet opcodePrefix="FE 61 01" id="646" />
		<packet opcodePrefix="FE 62 01" id="647" />
		<packet opcodePrefix="FE 63 01" id="648" />
		<packet opcodePrefix="FE 64 01" id="649" />
		<packet opcodePrefix="FE 65 01" id="654" />
		<packet opcodePrefix="FE 66 01" id="530" />
		<packet opcodePrefix="FE 67 01" id="526" />
		<packet opcodePrefix="FE 68 01" id="656" />
		<packet opcodePrefix="FE 69 01" id="657" />
		<packet opcodePrefix="FE 6A 01" id="658" />
		<packet opcodePrefix="FE 6B 01" id="659" />
		<packet opcodePrefix="FE 6C 01" id="660" />
		<packet opcodePrefix="FE 6D 01" id="531" />
		<packet opcodePrefix="FE 6E 01" id="528" />
		<packet opcodePrefix="FE 6F 01" id="662" />
		<packet opcodePrefix="FE 70 01" id="644" />
	</server>
</mapping>

=== Leantas/L2PacketAnalyzer/config/packets/login_legacy/opcode_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../schemata/mapping.xsd">
	<client>
		<packet opcodePrefix="00" id="LS_CM_AQ_LOGIN" />
		<packet opcodePrefix="02" id="LS_CM_REQUEST_SERVER_LOGIN" />
		<packet opcodePrefix="05" id="LS_CM_REQUEST_SERVER_LIST" />
	</client>
	<server>
		<packet opcodePrefix="00" id="LS_SM_SET_ENCRYPTION" />
		<packet opcodePrefix="01" id="LS_SM_LOGIN_FAIL_2" />
		<packet opcodePrefix="02" id="LS_SM_BLOCKED_ACCOUNT" />
		<packet opcodePrefix="03" id="LS_SM_LOGIN_OK" />
		<packet opcodePrefix="04" id="LS_SM_SERVER_LIST" />
		<packet opcodePrefix="06" id="LS_SM_PLAY_FAIL" />
		<packet opcodePrefix="07" id="LS_SM_PLAY_OK" />
		<packet opcodePrefix="08" id="LS_SM_ACCOUNT_KICKED" />
		<packet opcodePrefix="09" id="LS_SM_BLOCKED_ACCOUNT_WITH_MSG" />
	</server>
</mapping>

=== Leantas/L2PacketAnalyzer/config/packets/high_five/opcode_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../schemata/mapping.xsd">
	<client>
		<packet opcodePrefix="D0 83 00 01 00 00 00" id="325" />
		<packet opcodePrefix="D0 83 00 02 00 00 00" id="326" />
		<packet opcodePrefix="D0 83 00 03 00 00 00" id="327" />
		<packet opcodePrefix="D0 83 00 04 00 00 00" id="328" />
		<packet opcodePrefix="D0 83 00 05 00 00 00" id="329" />
		<packet opcodePrefix="D0 83 00 07 00 00 00" id="330" />
		<packet opcodePrefix="D0 83 00 08 00 00 00" id="331" />
		<packet opcodePrefix="D0 83 00 09 00 00 00" id="332" />
		<packet opcodePrefix="D0 83 00 0A 00 00 00" id="333" />
		<packet opcodePrefix="D0 83 00 0D 00 00 00" id="334" />
		<packet opcodePrefix="D0 83 00 0E 00 00 00" id="335" />
		<packet opcodePrefix="D0 83 00 0F 00 00 00" id="336" />
		<packet opcodePrefix="D0 83 00 10 00 00 00" id="337" />
		<packet opcodePrefix="D0 83 00 11 00 00 00" id="338" />
		<packet opcodePrefix="D0 83 00 12 00 00 00" id="339" />
		<packet opcodePrefix="D0 83 00 13 00 00 00" id="340" />
		<packet opcodePrefix="D0 83 00 14 00 00 00" id="341" />
		<packet opcodePrefix="D0 84 00" id="342" />
		<packet opcodePrefix="D0 85 00" id="343" />
		<packet opcodePrefix="D0 86 00" id="344" />
		<packet opcodePrefix="D0 87 00" id="345" />
		<packet opcodePrefix="D0 88 00" id="202" />
		<packet opcodePrefix="D0 89 00" id="288" />
		<packet opcodePrefix="D0 8A 00" id="289" />
		<packet opcodePrefix="D0 8B 00" id="290" />
		<packet opcodePrefix="D0 8C 00" id="291" />
		<packet opcodePrefix="D0 8D 00" id="309" />
		<packet opcodePrefix="D0 8E 00" id="311" />
		<packet opcodePrefix="D0 8F 00" id="312" />
		<packet opcodePrefix="D0 90 00" id="313" />
		<packet opcodePrefix="D0 91 00" id="346" />
		<packet opcodePrefix="D0 92 00" id="347" />
		<packet opcodePrefix="D0 93 00" id="322" />
		<packet opcodePrefix="D0 94 00" id="323" />
		<packet opcodePrefix="D0 95 00" id="324" />
	</client>
	<server>
		<packet opcodePrefix="FE BC 00" id="462" />
		<packet opcodePrefix="FE BD 00" id="484" />
		<packet opcodePrefix="FE BE 00" id="492" />
		<packet opcodePrefix="FE BF 00" id="493" />
		<packet opcodePrefix="FE C0 00" id="494" />
		<packet opcodePrefix="FE C1 00" id="495" />
		<packet opcodePrefix="FE C2 00" id="496" />
		<packet opcodePrefix="FE C3 00" id="497" />
		<packet opcodePrefix="FE C4 00" id="498" />
		<packet opcodePrefix="FE C5 00" id="499" />
		<packet opcodePrefix="FE C6 00" id="500" />
		<packet opcodePrefix="FE C7 00" id="501" />
		<packet opcodePrefix="FE C8 00" id="502" />
		<packet opcodePrefix="FE C9 00" id="503" />
		<packet opcodePrefix="FE CA 00" id="504" />
		<packet opcodePrefix="FE CB 00" id="505" />
		<packet opcodePrefix="FE CC 00" id="506" />
		<packet opcodePrefix="FE CD 00" id="507" />
		<packet opcodePrefix="FE CE 00" id="508" />
		<packet opcodePrefix="FE CF 00" id="509" />
		<packet opcodePrefix="FE D0 00" id="510" />
		<packet opcodePrefix="FE D1 00" id="511" />
		<packet opcodePrefix="FE D2 00" id="512" />
		<packet opcodePrefix="FE D3 00" id="513" />
		<packet opcodePrefix="FE D4 00" id="514" />
		<packet opcodePrefix="FE D5 00" id="457" />
		<packet opcodePrefix="FE D6 00" id="458" />
		<packet opcodePrefix="FE D7 00" id="459" />
		<packet opcodePrefix="FE D8 00" id="460" />
		<packet opcodePrefix="FE D9 00" id="537" />
		<packet opcodePrefix="FE DA 00" id="463" />
		<packet opcodePrefix="FE DB 00" id="466" />
		<packet opcodePrefix="FE DC 00" id="483" />
		<packet opcodePrefix="FE DD 00" id="485" />
		<packet opcodePrefix="FE DE 00" id="486" />
		<packet opcodePrefix="FE DF 00" id="515" />
		<packet opcodePrefix="FE E0 00" id="516" />
		<packet opcodePrefix="FE E1 00" id="517" />
		<packet opcodePrefix="FE E2 00" id="518" />
		<packet opcodePrefix="FE E3 00" id="519" />
		<packet opcodePrefix="FE E4 00" id="520" />
		<packet opcodePrefix="FE E5 00" id="521" />
		<packet opcodePrefix="FE E6 00" id="522" />
		<packet opcodePrefix="FE E7 00" id="523" />
		<packet opcodePrefix="FE E8 00" id="524" />
	</server>
</mapping>

=== Leantas/L2PacketAnalyzer/config/packets/lindvior_update_1/opcode_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../schemata/mapping.xsd">
	<client />
	<server>
		<removedPacket id="SM_USER_INFO"/> <!-- Ignored by client -->
		<removedPacket id="SM_NPC_INFO"/> <!-- Ignored by client -->
		<packet opcodePrefix="FE 5B 01" id="694" />
		<packet opcodePrefix="FE 5C 01" id="695" />
		<packet opcodePrefix="FE 5D 01" id="696" />
		<packet opcodePrefix="FE 5E 01" id="645" />
		<packet opcodePrefix="FE 5F 01" id="527" />
		<packet opcodePrefix="FE 60 01" id="646" />
		<packet opcodePrefix="FE 61 01" id="647" />
		<packet opcodePrefix="FE 62 01" id="648" />
		<packet opcodePrefix="FE 63 01" id="649" />
		<packet opcodePrefix="FE 64 01" id="654" />
		<packet opcodePrefix="FE 65 01" id="530" />
		<packet opcodePrefix="FE 66 01" id="526" />
		<packet opcodePrefix="FE 67 01" id="531" />
		<packet opcodePrefix="FE 68 01" id="528" />
		<packet opcodePrefix="FE 69 01" id="662" />
	</server>
</mapping>

=== Leantas/L2PacketAnalyzer/config/packets/glory_days/opcode_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../schemata/mapping.xsd">
	<client>
		<packet opcodePrefix="D0 C3 00" id="396" />
		<packet opcodePrefix="D0 C4 00" id="397" />
		<packet opcodePrefix="D0 C5 00" id="398" />
		<packet opcodePrefix="D0 C6 00" id="399" />
		<packet opcodePrefix="D0 C7 00" id="400" />
		<packet opcodePrefix="D0 C8 00" id="401" />
		<packet opcodePrefix="D0 C9 00" id="402" />
		<packet opcodePrefix="D0 CA 00" id="403" />
		<packet opcodePrefix="D0 D1 00" id="467" />
		<packet opcodePrefix="D0 D2 00" id="468" />
		<packet opcodePrefix="D0 D3 00" id="469" />
		<packet opcodePrefix="D0 D4 00" id="470" />
		<packet opcodePrefix="D0 D5 00" id="471" />
		<packet opcodePrefix="D0 D6 00" id="472" />
		<packet opcodePrefix="D0 D7 00" id="473" />
		<packet opcodePrefix="D0 D8 00" id="409" />
		<packet opcodePrefix="D0 D9 00" id="474" />
		<packet opcodePrefix="D0 DB 00" id="414" />
		<packet opcodePrefix="D0 DC 00" id="415" />
		<packet opcodePrefix="D0 DD 00" id="351" />
	</client>
	<server>
		<packet opcodePrefix="FE 35 01" id="607" />
		<packet opcodePrefix="FE 36 01" id="689" />
		<packet opcodePrefix="FE 37 01" id="690" />
		<packet opcodePrefix="FE 38 01" id="691" />
		<packet opcodePrefix="FE 39 01" id="692" />
		<packet opcodePrefix="FE 3A 01" id="608" />
		<packet opcodePrefix="FE 3B 01" id="609" />
		<packet opcodePrefix="FE 3C 01" id="617" />
		<packet opcodePrefix="FE 3D 01" id="618" />
		<packet opcodePrefix="FE 3E 01" id="619" />
		<packet opcodePrefix="FE 3F 01" id="632" />
		<packet opcodePrefix="FE 40 01" id="633" />
	</server>
</mapping>
