=== Leantas/L2PacketAnalyzer/config/schemata/packet.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.l2emu-unique.net" xmlns="http://www.l2emu-unique.net"
	elementFormDefault="qualified">

	<xs:element name="packet" type="packetType" />

	<xs:complexType name="packetType">
		<xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:choice>
					<xs:element name="bytes" type="bytesType" />
					<xs:element name="byte" type="dataType" />
					<xs:element name="unsignedByte" type="dataType" />
					<xs:element name="word" type="dataType" />
					<xs:element name="unsignedWord" type="dataType" />
					<xs:element name="dword" type="dataType" />
					<xs:element name="qword" type="dataType" />
					<xs:element name="single" type="dataType" />
					<xs:element name="double" type="dataType" />
					<xs:element name="string" type="dataType" /> <!-- nul-terminated string (default) -->
					<xs:element name="ntstring" type="dataType" /> <!-- nul-terminated string -->
					<xs:element name="sstring" type="dataType" /> <!-- sized string -->
					<xs:element name="loop" type="loopType" />
					<xs:element name="branch" type="branchType" />
				</xs:choice>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="id" type="xs:token" use="required" />
	</xs:complexType>

	<xs:complexType name="structureType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element name="bytes" type="bytesType" />
				<xs:element name="byte" type="dataType" />
				<xs:element name="unsignedByte" type="dataType" />
				<xs:element name="word" type="dataType" />
				<xs:element name="unsignedWord" type="dataType" />
				<xs:element name="dword" type="dataType" />
				<xs:element name="qword" type="dataType" />
				<xs:element name="single" type="dataType" />
				<xs:element name="double" type="dataType" />
				<xs:element name="string" type="dataType" /> <!-- nul-terminated string (default) -->
				<xs:element name="ntstring" type="dataType" /> <!-- nul-terminated string -->
				<xs:element name="sstring" type="dataType" /> <!-- sized string -->
				<xs:element name="loop" type="loopType" />
				<xs:element name="branch" type="branchType" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="loopType">
		<xs:complexContent>
			<xs:extension base="structureType">
				<xs:attribute name="id" type="xs:token" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="branchType">
		<xs:complexContent>
			<xs:extension base="structureType">
				<xs:attribute name="id" type="xs:token" />
				<xs:attribute name="condition" type="conditionType" />
				<xs:attribute name="description" type="xs:token" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="scriptAliasType">
		<xs:attribute name="id" type="xs:token" use="required" />
	</xs:complexType>

	<xs:complexType name="bytesType">
		<xs:sequence>
			<xs:element name="length" type="xs:unsignedInt" minOccurs="0" maxOccurs="1" />
			<xs:element name="scriptAlias" type="scriptAliasType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="alias" type="xs:token" use="required" />
		<xs:attribute name="type" type="interpreterType" />
		<xs:attribute name="optional" type="xs:boolean" default="false" />
	</xs:complexType>

	<xs:complexType name="dataType">
		<xs:sequence>
			<xs:element name="scriptAlias" type="scriptAliasType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:token" /> <!-- unique identifier for condition evaluation, loop and dynamic array sizing -->
		<xs:attribute name="alias" type="xs:token" use="required" />
		<xs:attribute name="mod" type="modifierType" />
		<xs:attribute name="type" type="interpreterType" />
		<!-- Marks this entry and everything else after as 'possibly inside the buffer' -->
		<xs:attribute name="optional" type="xs:boolean" default="false" />
	</xs:complexType>

	<xs:simpleType name="interpreterType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="AbilityWingIcon" />
			<xs:enumeration value="AdenaDistributionCancelReason" />
			<xs:enumeration value="Answer" />
			<xs:enumeration value="AirshipAction" />
			<xs:enumeration value="Alliance" />
			<xs:enumeration value="AllianceCrest" />
			<xs:enumeration value="AntiImpersonationRelation" />
			<xs:enumeration value="ASCII" />
			<xs:enumeration value="AuctionDuration" />
			<xs:enumeration value="AuctionItemGrade" />
			<xs:enumeration value="AuctionItemType" />
			<xs:enumeration value="AuctionListType" />
			<xs:enumeration value="Augmentation" />
			<xs:enumeration value="AuthDialog" />
			<xs:enumeration value="AuthResult" />
			<xs:enumeration value="Alphabet" /> <!-- Face/Hair -->
			<xs:enumeration value="BGR" />
			<xs:enumeration value="BlockedAccountDialogMessage" />
			<xs:enumeration value="BoardWindow" />
			<xs:enumeration value="Cabal" />
			<xs:enumeration value="CardGame" />
			<xs:enumeration value="CastleResidenceInfo" /> <!-- CLEO -->
			<xs:enumeration value="CharacterClass" />
			<xs:enumeration value="CharacterClassType" />
			<xs:enumeration value="Chat" />
			<xs:enumeration value="ChCrReason" />
			<xs:enumeration value="ChDeReason" />
			<xs:enumeration value="CompassZone" />
			<xs:enumeration value="CommunityBoardHtml" />
			<xs:enumeration value="ConsultationRanking" />
			<xs:enumeration value="Cubic" />
			<xs:enumeration value="Controller" />
			<xs:enumeration value="CurrentCrops" />
			<xs:enumeration value="DamageTypes" />
			<xs:enumeration value="DeclaredSiegeTime" />
			<xs:enumeration value="DirectDrawSurface" />
			<xs:enumeration value="DuelTeam" />
			<xs:enumeration value="ElementMask" />
			<xs:enumeration value="ElementPower" />
			<xs:enumeration value="ElementType" />
			<xs:enumeration value="EnchantEffect" />
			<xs:enumeration value="EnchantResult" />
			<xs:enumeration value="Event" />
			<xs:enumeration value="ExNpcInfoState" />
			<xs:enumeration value="Festival" />
			<xs:enumeration value="FishingAction" />
			<xs:enumeration value="FishingActionResult" />
			<xs:enumeration value="FishStrength" />
			<xs:enumeration value="FlyPathNode" />
			<xs:enumeration value="FlyType" />
			<xs:enumeration value="FriendStatusUpdate" />
			<xs:enumeration value="GameServerListVersion" />
			<xs:enumeration value="GameServerName" />
			<xs:enumeration value="GameServerTypes" />
			<xs:enumeration value="GameTime" />
			<xs:enumeration value="Gauge" />
			<xs:enumeration value="GmView" />
			<xs:enumeration value="Henna" />
			<xs:enumeration value="HideoutType" />
			<xs:enumeration value="HitTypes" />
			<xs:enumeration value="Hp" />
			<xs:enumeration value="ImmutableNpcString" />
			<xs:enumeration value="ImmutableSystemMessage" />
			<xs:enumeration value="Instance" />
			<xs:enumeration value="InventorySlot" />
			<xs:enumeration value="IPv4" />
			<xs:enumeration value="Item" />
			<xs:enumeration value="ItemChange" />
			<xs:enumeration value="ItemInfoEx" />
			<xs:enumeration value="ItemRedist" />
			<xs:enumeration value="ItemRestriction" />
			<xs:enumeration value="ItemType1" />
			<xs:enumeration value="ItemType2" />
			<xs:enumeration value="KnownlistState" />
			<xs:enumeration value="KrateiState" />
			<xs:enumeration value="LoginFailureReason" />
			<xs:enumeration value="LootRights" />
			<xs:enumeration value="LottoNumbers" />
			<xs:enumeration value="Lure" />
			<xs:enumeration value="MacroChange" />
			<xs:enumeration value="MacroCommandType" />
			<xs:enumeration value="MacroIcon" />
			<xs:enumeration value="Mailbox" />
			<xs:enumeration value="MailChange" />
			<xs:enumeration value="MailMessageType" />
			<xs:enumeration value="ManaConsumptionType" />
			<xs:enumeration value="ManufactureResult" />
			<xs:enumeration value="MarkerChange" />
			<xs:enumeration value="MatchMessage" />
			<xs:enumeration value="MatchState" />
			<xs:enumeration value="Mentoring" /> <!-- CLEO -->
			<xs:enumeration value="MercenaryName" />
			<xs:enumeration value="MessageDirection" />
			<xs:enumeration value="MessageRefusalAction" />
			<xs:enumeration value="MillisRemaining" />
			<xs:enumeration value="MonsterRaceBetMultiplier" />
			<xs:enumeration value="MountType" />
			<xs:enumeration value="MoveType" />
			<xs:enumeration value="MuseumStat" />
			<xs:enumeration value="MyInventorySlot" />
			<xs:enumeration value="NevitHuntingProgress" />
			<xs:enumeration value="Npc" />
			<xs:enumeration value="NpcState" />
			<xs:enumeration value="NpcSubtype" />
			<xs:enumeration value="NpcTitleColor" />
			<xs:enumeration value="NpcType" /> <!-- CLEO -->
			<xs:enumeration value="ObjectID" />
			<xs:enumeration value="OlympiadMatch" />
			<xs:enumeration value="OlympiadSide" />
			<xs:enumeration value="OlympiadSpectation" />
			<xs:enumeration value="Parameter" />
			<xs:enumeration value="PartyChange" />
			<xs:enumeration value="PartyMatchingLevels" />
			<xs:enumeration value="PartyMemberType" />
			<xs:enumeration value="PartyRoomRegion" />
			<xs:enumeration value="PcTimer" />
			<xs:enumeration value="PersonalStoreType" />
			<xs:enumeration value="PetitionType" /> <!-- CLEO -->
			<xs:enumeration value="PlayerAction" />
			<xs:enumeration value="PlayerCommand" />
			<xs:enumeration value="Pledge" />
			<xs:enumeration value="PledgeBase" />
			<xs:enumeration value="PledgeCrest" />
			<xs:enumeration value="PledgePowerRank" />
			<xs:enumeration value="PledgePowerUpdate" />
			<xs:enumeration value="PledgePrivileges" />
			<xs:enumeration value="PledgeRank" />
			<xs:enumeration value="PledgeUnit" />
			<xs:enumeration value="PledgeWarTab" />
			<xs:enumeration value="PointOfView" />
			<xs:enumeration value="PreformattedHtml" />
			<xs:enumeration value="Pvp" />
			<xs:enumeration value="Quest" />
			<xs:enumeration value="QuestState" />
			<xs:enumeration value="Race" />
			<xs:enumeration value="Recipe" />
			<xs:enumeration value="RecipeBook" />
			<xs:enumeration value="Regeneration" />
			<xs:enumeration value="RevivalLocation" />
			<xs:enumeration value="RelationPacketType" />
			<xs:enumeration value="RelationTypes" />
			<xs:enumeration value="RoomMembership" />
			<xs:enumeration value="Rotation" />
			<xs:enumeration value="Scene" />
			<xs:enumeration value="ScreenMessagePosition" />
			<xs:enumeration value="Seal" />
			<xs:enumeration value="SecAuthDialog" />
			<xs:enumeration value="SecAuthSetup" />
			<xs:enumeration value="SecondsLeftToTime" />
			<xs:enumeration value="SecondsSinceEpoch" />
			<xs:enumeration value="ServitorStatus" />
			<xs:enumeration value="ServitorType" />
			<xs:enumeration value="SevenSignsPeriod" />
			<xs:enumeration value="SevenSignsRecordTab" />
			<xs:enumeration value="Sex" />
			<xs:enumeration value="ShadowMana" />
			<xs:enumeration value="SiegeDefenderStatus" />
			<xs:enumeration value="SiegeRegistration" />
			<xs:enumeration value="SiegeSide" />
			<xs:enumeration value="Skill" />
			<xs:enumeration value="SkillEnchant" />
			<xs:enumeration value="SkillListType" />
			<xs:enumeration value="SkyColor" />
			<xs:enumeration value="SoulshotGrade" />
			<xs:enumeration value="SoundType" />
			<xs:enumeration value="StaticObject" />
			<xs:enumeration value="SysString" />
			<xs:enumeration value="TargetDeselectionMode" />
			<xs:enumeration value="TargetSelectionMode" />
			<xs:enumeration value="TeamColor" />
			<xs:enumeration value="TimeRemaining" />
			<xs:enumeration value="TitleColor" />
			<xs:enumeration value="ToggleableEtcState" />
			<xs:enumeration value="Token" />
			<xs:enumeration value="TradeResult" />
			<xs:enumeration value="TradeUpdate" />
			<xs:enumeration value="Transformation" />
			<xs:enumeration value="TutorialEvents" />
			<xs:enumeration value="TutorialHtmlWindowType" />
			<xs:enumeration value="UnknownTeam" />
			<xs:enumeration value="UserRoles" />
			<xs:enumeration value="UsmVideo" /> <!-- CLEO -->
			<xs:enumeration value="UpdatableAttribute" />
			<xs:enumeration value="VitalityLevel" />
			<xs:enumeration value="WaitType" />
			<xs:enumeration value="Warehouse" />
			<xs:enumeration value="WarehouseUsageResult" />
			<xs:enumeration value="WeaponStatus" />
			<xs:enumeration value="YesOrNo" />

			<xs:enumeration value="ave.AbnormalVisualEffect" />
			<xs:enumeration value="ave.AbnormalVisualEffectMask" />
			<xs:enumeration value="ave.AbnormalVisualEffectMask2" />

			<xs:enumeration value="commission.ItemCategory" />

			<xs:enumeration value="equip.EquipmentSlot" />
			<xs:enumeration value="equip.EquipmentState" />
			<xs:enumeration value="equip.ExUserEquipSlot1" />
			<xs:enumeration value="equip.ExUserEquipSlot2" />
			<xs:enumeration value="equip.ExUserEquipSlot3" />
			<xs:enumeration value="equip.ExUserEquipSlot4" />
			<xs:enumeration value="equip.ExUserEquipSlot5" />
			<xs:enumeration value="equip.PaperdollMask" />

			<xs:enumeration value="party.PartyMatchingAffilation" />
			<xs:enumeration value="party.PartyMatchingListMode" />

			<xs:enumeration value="pledge.ApplicationMode" />
			<xs:enumeration value="pledge.ApplicationResponse" />
			<xs:enumeration value="pledge.AllyCrestDDS" />
			<xs:enumeration value="pledge.PledgeAdvertisement" />
			<xs:enumeration value="pledge.PledgeCrestDDS" />
			<xs:enumeration value="pledge.PledgeKarma" />
			<xs:enumeration value="pledge.PledgeSearchType" />
			<xs:enumeration value="pledge.PledgeStatus" />
			<xs:enumeration value="pledge.PledgeWarReply" />

			<xs:enumeration value="product.Product" />
			<xs:enumeration value="product.ProductFrontPageSectionMask" />
			<xs:enumeration value="product.ProductListType" />
			<xs:enumeration value="product.ProductMarketTime" />
			<xs:enumeration value="product.ProductModifier" />
			<xs:enumeration value="product.ProductPriceType" />
			<xs:enumeration value="product.ProductRepurchaseInterval" />
			<xs:enumeration value="product.ProductStoreTab" />

			<xs:enumeration value="quest.QuestCompletion" />
			
			<xs:enumeration value="shortcut.ShortcutActor" />
			<xs:enumeration value="shortcut.ShortcutSlotBase10" />
			<xs:enumeration value="shortcut.ShortcutSlotBase12" />
			<xs:enumeration value="shortcut.ShortcutType" />

			<xs:enumeration value="skill.SkillLevel" />

			<xs:enumeration value="structure.ExNpcInfoFieldMask1" />
			<xs:enumeration value="structure.ExNpcInfoFieldMask2" />
			<xs:enumeration value="structure.ExNpcInfoFieldMask3" />
			<xs:enumeration value="structure.ExNpcInfoFieldMask4" />
			<xs:enumeration value="structure.ExNpcInfoFieldMask5" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="modifierType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="MinusOne" />
			<xs:enumeration value="NewLotteryEvent" />
			<xs:enumeration value="PlusOne" />
			<xs:enumeration value="PlusFiftyFive" />
			<xs:enumeration value="ShiftLeft8" />
			<xs:enumeration value="ShiftLeft16" />
			<xs:enumeration value="ShiftLeft24" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="conditionType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="BlockUnblockPlayer" />
			<xs:enumeration value="DefaultChat" />
			<xs:enumeration value="FerryShout" />
			<xs:enumeration value="GenericItem" />
			<xs:enumeration value="LotteryTicket" />
			<xs:enumeration value="MonsterRaceTicket" />
			<xs:enumeration value="MutableSM" />
			<xs:enumeration value="Negative" />
			<xs:enumeration value="NonNegative" />
			<xs:enumeration value="NonPositive" />
			<xs:enumeration value="NotPrivateMessage" />
			<xs:enumeration value="PledgePowerUpdate" />
			<xs:enumeration value="PledgeUnitSkills" />
			<xs:enumeration value="Positive" />
			<xs:enumeration value="PrivateMessage" />
			<xs:enumeration value="Zero" />
			
			<xs:enumeration value="airship.DefaultAction" />
			<xs:enumeration value="airship.Movement" />
			<xs:enumeration value="airship.Teleport" />
			
			<xs:enumeration value="bitmask.Bit0" />
			<xs:enumeration value="bitmask.Bit1" />
			<xs:enumeration value="bitmask.Bit2" />
			<xs:enumeration value="bitmask.Bit3" />
			<xs:enumeration value="bitmask.Bit4" />
			<xs:enumeration value="bitmask.Bit5" />
			<xs:enumeration value="bitmask.Bit6" />
			<xs:enumeration value="bitmask.Bit7" />
			<xs:enumeration value="bitmask.NotAllBits" />
			
			<xs:enumeration value="equip.EquipableItemType" />
			<xs:enumeration value="equip.NewlyEquipped" />
			<xs:enumeration value="equip.NonEquipableItemType" />
			<xs:enumeration value="equip.Unequipped" />
			
			<xs:enumeration value="event.EvaInferno" />
			
			<xs:enumeration value="friend.ClassChange" />
			<xs:enumeration value="friend.LevelChange" />
			
			<xs:enumeration value="museum.AwakenedClass" />
			<xs:enumeration value="museum.DefaultStat" />
			<xs:enumeration value="museum.Duration" />
			<xs:enumeration value="museum.Grade" />
			<xs:enumeration value="museum.NotDuration" />
			<xs:enumeration value="museum.Npc" />
			
			<xs:enumeration value="param.CharacterClass" />
			<xs:enumeration value="param.Damage" />
			<xs:enumeration value="param.Element" />
			<xs:enumeration value="param.Fstring" />
			<xs:enumeration value="param.Instance" />
			<xs:enumeration value="param.Item" />
			<xs:enumeration value="param.Item2" />
			<xs:enumeration value="param.MutableFstring" />
			<xs:enumeration value="param.Npc" />
			<xs:enumeration value="param.NumberValue" />
			<xs:enumeration value="param.Player" />
			<xs:enumeration value="param.PledgeBase" />
			<xs:enumeration value="param.Quantity" />
			<xs:enumeration value="param.Skill" />
			<xs:enumeration value="param.SmallNumberValue" />
			<xs:enumeration value="param.StringValue" />
			<xs:enumeration value="param.Sysstring" />
			<xs:enumeration value="param.TinyNumberValue" />
			<xs:enumeration value="param.Zone" />
			
			<xs:enumeration value="relation.Ack" />
			<xs:enumeration value="relation.Multiple" />
			<xs:enumeration value="relation.Single" />
			
			<xs:enumeration value="serverlist.ServerListC1" />
			<xs:enumeration value="serverlist.ServerListC2" />
			
			<xs:enumeration value="servitor.Pet" />
			<xs:enumeration value="servitor.Summon" />
			
			<xs:enumeration value="shortcut.ActionShortcut" />
			<xs:enumeration value="shortcut.DefaultShortcut" />
			<xs:enumeration value="shortcut.ItemShortcut" />
			<xs:enumeration value="shortcut.MacroShortcut" />
			<xs:enumeration value="shortcut.RecipeShortcut" />
			<xs:enumeration value="shortcut.SkillShortcut" />
			
			<xs:enumeration value="status.CurrentCp" />
			<xs:enumeration value="status.DefaultAttribute" />
			<xs:enumeration value="status.Hp" />
			
			<xs:enumeration value="tab.Festival" />
			<xs:enumeration value="tab.General" />
			<xs:enumeration value="tab.Projection" />
			<xs:enumeration value="tab.SealStatus" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Leantas/L2PacketAnalyzer/config/packets/prelude_pts/server/MoveToLocation.xml
<?xml version="1.0" encoding="UTF-8"?>
<packet id="SM_MOVE_TO_LOCATION" xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../../schemata/packet.xsd">
	<dword alias="Actor OID" type="ObjectID">
		<scriptAlias id="OIL_OBJECT_ID" />
		<scriptAlias id="fspawn_walker_oid" />
	</dword>
	<dword alias="Destination X">
		<scriptAlias id="OIL_OBJECT_DESTINATION_X" />
	</dword>
	<dword alias="Destination Y">
		<scriptAlias id="OIL_OBJECT_DESTINATION_Y" />
	</dword>
	<dword alias="Destination Z">
		<scriptAlias id="OIL_OBJECT_DESTINATION_Z" />
	</dword>
	<dword alias="Current X">
		<scriptAlias id="OIL_OBJECT_X_SERVER" />
	</dword>
	<dword alias="Current Y">
		<scriptAlias id="OIL_OBJECT_Y_SERVER" />
	</dword>
	<dword alias="Current Z">
		<scriptAlias id="OIL_OBJECT_Z_SERVER" />
	</dword>
</packet>

=== Leantas/L2PacketAnalyzer/config/packets/high_five/server/SSQStatus.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file was automatically generated when converting from the legacy definition format. -->
<!-- The packet definition might be a clone of an existing definition in an earlier protocol version. -->
<!-- If so, delete this file. Otherwise, delete this comment (or replace with comments on what has changed). -->
<packet id="279" xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../../schemata/packet.xsd">
	<byte alias="Page" type="SevenSignsRecordTab" id="cond_1" />
	<byte alias="Current period" type="SevenSignsPeriod" />
	<branch id="cond_1" condition="tab.General">
		<dword alias="Current cycle" />
		<dword alias="Period info" type="ImmutableSystemMessage" />
		<dword alias="Period duration info" type="ImmutableSystemMessage" />

		<byte alias="Viewer's cabal" type="Cabal" />
		<byte alias="Viewer's seal" type="Seal" />
		<qword alias="Contribution score" />
		<qword alias="Ancient adena to be collected" />

		<qword alias="Dusk contribution score" />
		<qword alias="Dusk festival score" />
		<qword alias="Dusk total score" />
		<byte alias="Dusk total %" />
		<qword alias="Dawn contribution score" />
		<qword alias="Dawn festival score" />
		<qword alias="Dawn total score" />
		<byte alias="Dawn total %" />
	</branch>
	<branch id="cond_1" condition="tab.Festival">
		<word alias="1" />
		<byte alias="Festival count" id="index_0" />
		<loop id="index_0">
			<byte alias="Festival" type="Festival" />
			<dword alias="Minimal score" />
			<qword alias="Dusk score" />
			<byte alias="Achiever party size" id="index_1" />
			<loop id="index_1">
				<string alias="Achiever name" />
			</loop>
			<qword alias="Dawn score" />
			<byte alias="Achiever party size" id="index_1" />
			<loop id="index_1">
				<string alias="Achiever name" />
			</loop>
		</loop>
	</branch>
	<branch id="cond_1" condition="tab.SealStatus">
		<byte alias="% of registrations to retain an owned seal (on victory)" />
		<byte alias="% of registrations to claim a seal (on victory)" />
		<byte alias="Seal count" id="index_0" />
		<loop id="index_0">
			<byte alias="Seal" type="Seal" />
			<byte alias="Owner" type="Cabal" />
			<byte alias="% of Dusk registrations" />
			<byte alias="% of Dawn registrations" />
		</loop>
	</branch>
	<branch id="cond_1" condition="tab.Projection">
		<byte alias="Winning cabal" type="Cabal" />
		<byte alias="Seal count" id="index_0" />
		<loop id="index_0">
			<byte alias="Seal" type="Seal" />
			<byte alias="Expected owner" type="Cabal" />
			<dword alias="Explanation" type="ImmutableSystemMessage" />
		</loop>
	</branch>
</packet>

=== Leantas/L2PacketAnalyzer/config/packets/infinite_odyssey/server/ExPartySpelledInfoUpdate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Skill level WORDs changed to DWORDs -->
<packet id="650" xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../../schemata/packet.xsd">
	<dword alias="0" />
	<dword alias="Party member OID" type="ObjectID" />
	<dword alias="Removed effects" id="removed" />
	<loop id="removed">
		<dword alias="Skill" type="Skill">
			<scriptAlias id="__INTERP_CORRECTION_SKILL_ID" />
		</dword>
		<dword alias="Level" type="skill.SkillLevel"> <!-- NEW -->
			<scriptAlias id="__INTERP_CORRECTION_SKILL_LEVEL" />
		</dword>
		<dword alias="0" />
	</loop>
	<dword alias="Added effects" id="added" />
	<loop id="added">
		<dword alias="Skill" type="Skill">
			<scriptAlias id="__INTERP_CORRECTION_SKILL_ID" />
		</dword>
		<dword alias="Level" type="skill.SkillLevel"> <!-- NEW -->
			<scriptAlias id="__INTERP_CORRECTION_SKILL_LEVEL" />
		</dword>
		<dword alias="0" />
		<word alias="Time left" type="TimeRemaining" />
	</loop>
</packet>

=== Leantas/L2PacketAnalyzer/config/packets/valiance/server/ExPledgeRecruitInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file was automatically generated when converting from the legacy definition format. -->
<!-- The packet definition might be a clone of an existing definition in an earlier protocol version. -->
<!-- If so, delete this file. Otherwise, delete this comment (or replace with comments on what has changed). -->
<packet id="623" xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../../schemata/packet.xsd">
	<string alias="Pledge Name" />
	<string alias="Leader Name" />
	<dword alias="Pledge Level" />
	<dword alias="1" />
	<dword alias="Sub Unit Count" id="index_0" />
	<loop id="index_0">
		<dword alias="Sub Unit Type" type="PledgeUnit" />
		<string alias="Sub Unit Name" />
	</loop>
</packet>

=== Leantas/L2PacketAnalyzer/config/packets/prelude_pts/server/GMViewQuestInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<packet id="SM_GM_VIEW_QUEST_INFO" xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../../schemata/packet.xsd">
	<string alias="Player name" />

	<!-- QuestList packet below -->
	<word alias="Quest count" id="quest_cnt" />
	<loop id="quest_cnt">
		<dword alias="Quest" type="Quest" />
	</loop>
	<word alias="Quest item count" id="item_cnt" />
	<loop id="item_cnt">
		<dword alias="Item OID" type="ObjectID">
			<scriptAlias id="OIC_ITEM_OID" />
		</dword>
		<dword alias="Item" type="Item">
			<scriptAlias id="OIC_ITEM_TEMPLATE" />
		</dword>
		<dword alias="Amount" />
		<word alias="" />
	</loop>
</packet>

=== Leantas/L2PacketAnalyzer/config/packets/prelude_pts/server/MagicSkillUse.xml
<?xml version="1.0" encoding="UTF-8"?>
<packet id="SM_MAGIC_SKILL_USE" xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../../schemata/packet.xsd">
	<dword alias="Caster OID" type="ObjectID">
		<scriptAlias id="HLE_CASTER_OID" />
	</dword>
	<dword alias="Primary target OID" type="ObjectID">
		<scriptAlias id="HLE_TARGET_OID" />
	</dword>
	<dword alias="Skill" type="Skill">
		<scriptAlias id="__INTERP_CORRECTION_SKILL_ID" />
		<scriptAlias id="HLE_SKILL_ID" />
	</dword>
	<dword alias="Skill level" type="skill.SkillLevel">
		<scriptAlias id="__INTERP_CORRECTION_SKILL_LEVEL" />
		<scriptAlias id="HLE_SKILL_LEVEL" />
	</dword>
	<dword alias="Cast time" type="MillisRemaining">
		<scriptAlias id="HLE_CAST_TIME" />
	</dword>
	<dword alias="Reuse delay" type="MillisRemaining">
		<scriptAlias id="HLE_COOL_TIME" />
	</dword>
</packet>

=== Leantas/L2PacketAnalyzer/config/packets/gracia_final/client/SetPrivateStoreBuyList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Item amount/price is now a QWORD -->
<packet id="CM_SET_PRIVATE_STORE_BUY_LIST" xmlns="http://www.l2emu-unique.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.l2emu-unique.net ../../../schemata/packet.xsd">
	<dword alias="Offer count" id="index_0" />
	<loop id="index_0">
		<dword alias="Item" type="Item" id="is_ticket" />

		<branch id="is_ticket" condition="GenericItem">
			<word alias="Enchant level" />
			<word alias="Name exists" type="YesOrNo" />
		</branch>
		<branch id="is_ticket" condition="LotteryTicket">
			<unsignedWord alias="Selected numbers (truncated)" type="LottoNumbers" />
			<word alias="0" /> <!-- Please. Explain this to me. -->
		</branch>
		<branch id="is_ticket" condition="MonsterRaceTicket">
			<word alias="Race number" />
			<!-- Client reports exactly the same as server sends to it, so first time is correct -->
			<word alias="Actual bet multiplier / (100^([number of times owner set up the store without re-adding the item] - 1))" type="MonsterRaceBetMultiplier" />
		</branch>

		<qword alias="Quantity" />
		<qword alias="Price (per single unit)" />
	</loop>
</packet>
